on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Quarto Render

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Clean _book dir
        run: if [ -d _book ]; then rm -r _book; fi

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: _book

      - run: git checkout cf-pages
      - run: if [ -d book ]; then rm -r book; fi
      - run: mv _book book

      - name: Commit site changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add book
          git commit -m "Update site"
          git push
