on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Quarto Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Clean _book dir
        run: if [ -d _book ]; then rm -r _book; fi

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # This renders to the current working directory
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: _book

      - name: Move rendered book to cf-pages branch
        run: |
          git checkout cf-pages
          if [ -d _book ]; then rm -r _book; fi
